### ISSUE TITLE
Externalize freemarker config

### ISSUE THREAD

**Issue by dannypurcell** [tkrille/dropwizard-template-config#11]
Thanks for posting this for everyone! It is a life saver when building dropwizard in docker containers!

We got to a point where we would like to use the `<include "path">` to break up our config in to multiple files and hit a snag. It looks like the freemarker config does not set a template loader by default so we had to bypass `TemplateConfigBundle ` and override `TemplateConfigurationSourceProvider ` to set one.
<pre>
ERROR de.thomaskrille.dropwizard_template_config.redist.freemarker.runtime: Error executing FreeMarker template
! de.thomaskrille.dropwizard_template_config.redist.freemarker.template.TemplateNotFoundException: Don't know where to load template "test/child_config.yaml" from because the "template_loader" FreeMarker setting wasn't set (Configuration.setTemplateLoader), so it's null.
! at de.thomaskrille.dropwizard_template_config.redist.freemarker.template.Configuration.getTemplate(Configuration.java:1584)
! at de.thomaskrille.dropwizard_template_config.redist.freemarker.core.Environment.getTemplateForInclusion(Environment.java:2046)
! at de.thomaskrille.dropwizard_template_config.redist.freemarker.core.Include.accept(Include.java:157)
! ... 12 common frames omitted
! Causing: de.thomaskrille.dropwizard_template_config.redist.freemarker.core._MiscTemplateException: Template inclusion failed (for parameter value "test/child_config.yaml"):
! Don't know where to load template "test/child_config.yaml" from because the "template_loader" FreeMarker setting wasn't set (Configuration.setTemplateLoader), so it's null.
</pre>
 
If you don't mind having the bundle support this use case, it would be handy to have a path to pass in a [Configuration](https://github.com/tkrille/dropwizard-template-config/blob/master/src/main/java/de/thomaskrille/dropwizard_template_config/TemplateConfigurationSourceProvider.java#L47
) or some settings for it.

Thanks again!

**Comment by tkrille** [comment]
Hi @dannypurcell,

first of all thanks for your interest in this bundle. I'm happy to hear how helpful it is to you. I'm also sorry for this late reply, but I'm facing some kind of medical issue right now. Nevertheless, I'm happy to add this feature for you. Making includes possible was something I initially thought about, too, but I never experienced the need myself.

Anyways, I also wondered how to implement it. I mean, should includes be from the file system or the class path? Or maybe both and one can make the source and include dir configurable? If I understand you correctly, you want to include partials from the file system?

There's also a little problem: because this bundle does its work before the configuration has been loaded, how should one configure the include path? Should it be the dirname of the supplied config file? Should it be fixed during compile time? What do you think would work for your use case?

Greetings

Thomas

**Comment by dannypurcell** [comment]
I think we might be pretty slick to have it default to a classpath lookup but look for an environment variable or java property to override that. However, that is just a guess so it's probably not a perfect fit for all cases.
For the bundle's part it might be best to let the user pass that in via the constructor or setters.

**Comment by tkrille** [comment]
Alright, thanks for the explanation. I think we should start small here and extend the feature as needed. So I will do the following:

- Only support includes from the classpath for now.
- Configure the path within the classpath, where the includes are located, when creating a new bundle instance, e.g. as constructor parameter.
  - If the path is not configured, the behavior will be like now, i.e. startup will fail, if an include directive is used.

Does that work for you?

**Comment by dannypurcell** [comment]
Sorry for taking a while to reply. 
I think that will work for our case. As a shim, we have another bootstrap module doing essentially what you describe so this enhancement should allow us to replace that.

**Comment by tkrille** [comment]
This should be working now with the current master. You can test it if you like. Otherwise I will just make a new release: 1.2.0

**Comment by dannypurcell** [comment]
Thanks for working on this!
I finally got a chance to try it out yesterday. The mechanism seems to work as intended. 
Unfortunately, the freemarker system does not seem to have a good way to indent included text so I could not come up with a nice way to get the indenting right without pushing that responsibility off to my consumers.
Still, the actual include support is looking good! Thanks again!

**Comment by tkrille** [comment]
Sorry for the delay, but: I've just released version 1.2.0. It should be available on the central in some minutes.
