### ISSUE TITLE
Proposal: Add option to write final config to a file

### ISSUE THREAD

**Issue by jklukas** [tkrille/dropwizard-template-config#12]
We're currently using a config templater we built in-house as a small extension to Dropwizard's EnvironmentVariableSubsitutor, but this project looks like a significantly better-thought-out approach, so I'm going to try to advocate for us to switch.

One feature we built into our solution was the ability to write out the final config that gets passed back to Dropwizard. That's been helpful in debugging since we can reference the exact YAML that dropwizard is seeing. Would you be open to a PR to add that feature here?

I'm imagining adding an `outputPath` member to `TemplateConfigBundleConfiguration`. Then there would be a conditional right before [this line in `TemplateConfigurationSourceProvider`](https://github.com/tkrille/dropwizard-template-config/blob/6b30594af6898ea91b169eeb2123594885789a26/src/main/java/de/thomaskrille/dropwizard_template_config/TemplateConfigurationSourceProvider.java#L73) to check for a configured output path and write the byte array to that path before returning the stream.

**Comment by tkrille** [comment]
Hi @jklukas,

thanks for your interest in my bundle. This sounds like a nice feature and i'd be very happy to get a PR for this feature from you. Your implementation approach sounds good to me, so go for it! :)

**Comment by tkrille** [comment]
Closed by #15.
