### ISSUE TITLE
Add option to include config snippets based on file path rather than resource

### ISSUE THREAD

**Issue by jklukas** [tkrille/dropwizard-template-config#19]
We currently use Freemarker's `setClassForTemplateLoading(getClass(), includePath)` in order to define where to look for snippets to include. This requires that the snippets be defined as a resource in the classpath.

Before looking into the details of this project's `includePath` feature, I had assumed that `includePath` would be a filesystem path rather than a resource path. Indeed, I think that should be a supported option.

@tkrille - Would you be open to a PR adding filesystem-based includes as an option? I would propose changing the existing `includePath()` method to `resourceIncludePath()` (we could retain `includePath` for compatibility and mark it as deprecated) and add a new `fileIncludePath()` method whose argument would be passed to Freemarker's `setDirectoryForTemplateLoading()` rather than `setClassForTemplateLoading`.

Alternately, we could keep the `includePath` name, but add an additional signature `includePath(String path, PathType pathType)` where the second argument is an enum value. We'd define `PathType` to be either "resource" or "file".

**Comment by tkrille** [comment]
Hi @jklukas,

thanks again for making this project better :) The feature you are proposing, was already discussed in the [original issue](https://github.com/tkrille/dropwizard-template-config/issues/11) about includes. Back then I've decided to start the whole includes feature as simple as possible, which was only using resources from the classpath. But extending this to regular files in the file system was already planned for a future release.

So, yes, I'm more than open and very grateful for a PR that adds this feature. Your solution with 2 new methods and keeping the `includePath` method, which will just delegate to `resourceIncludePath`, looks very good to me. We should also deprecate the `includePath` method, so it can be removed in some later release. One question has still to be answered: If someone configures both, `resourceIncludePath` and `fileIncludePath`, what should happen? Has one option a precedence over the other or should startup fail with an `IllegalStateException`? Or something else? What do you think? At this time, I think throwing an exception might be the best way to avoid confusion and wrong configurations. But I have not thought this thru thoroughly.

**Comment by tkrille** [comment]
Another implementation approach would be to leave the `includePath` as is, but add a configuration method to set, how the bundle will interpret the path, i.e. `includePathType()`. This method will be passed an enum (or something) like `IncludePathType.CLASSPATH` or `IncludePathType.FILE_SYSTEM`. I think this was my original idea to solve the issue we're discussing here. But now that I write it down here, it feels overly complex and somehow unclean to do so. But it would solve the ambiguity, when calling both methods. What do you think?

**Comment by jklukas** [comment]
Two separate methods and an `IllegalStateException` if both are used seems the best option to me. I'll work on a PR following that model.

**Comment by tkrille** [comment]
Closed with #20
