### ISSUE TITLE
Add utility to parse and split URLs

### ISSUE THREAD

**Issue by tkrille** [tkrille/dropwizard-template-config#4]
This might be interesting for users of Heroku or other PaaS that define the database connection parameters as a single URL.

**Comment by yunspace** [comment]
Yes that would be handy, applies to Docker also. We currently specify 4 ENV variables for DB... pain...

**Comment by tkrille** [comment]
Alright, I will try to realize this as part of release 1.2.0 if it's still relevant for anybody.

**Comment by tkrille** [comment]
Re-scheduled for a later version, as nobody seems to be interested.
